/* eslint-disable react-refresh/only-export-components */

import ThemeProvider from '@/components/ThemeProvider';
import { AuthProvider } from '@contexts/AuthContext';

import './globals.css';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export type RootLayoutProps = {
  children: ReactNode;
};

// due next-themes, we have to suppress hydration warnings, can be improved later

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
